"""
User profiles — 10 scenarios covering all trust levels and histories.
Each profile tells a different story and changes how the pipeline behaves.
"""

PROFILES = [
    {
        "id": 1,
        "name": "Sarah M.",
        "member_since": "3 years",
        "bookings": 12,
        "past_disputes": 0,
        "refund_requests": 1,
        "trust_score": 87,
        "verified": True,
        "device": "Known device",
        "account_status": "Verified ✓",
        "pipeline_note": "Standard happy path. High trust, clean history. Smooth pipeline, standard queue, benefit of doubt on refunds.",
        "story": "Long-standing member, consistent booking history, no red flags.",
    },
    {
        "id": 2,
        "name": "Alex K.",
        "member_since": "2 weeks",
        "bookings": 1,
        "past_disputes": 0,
        "refund_requests": 0,
        "trust_score": 34,
        "verified": True,
        "device": "New device",
        "account_status": "Verified ✓",
        "pipeline_note": "New user — risk model skeptical despite clean intent. More friction, faster human escalation.",
        "story": "First booking, first problem. Legitimately new but system can't know that yet.",
    },
    {
        "id": 3,
        "name": "Marcus T.",
        "member_since": "3 years",
        "bookings": 18,
        "past_disputes": 6,
        "refund_requests": 9,
        "trust_score": 28,
        "verified": True,
        "device": "Known device",
        "account_status": "Verified ✓",
        "pipeline_note": "Long tenure but pattern of disputes. Guardrails tighten, refund requires human approval.",
        "story": "3 years of account age but 9 refund requests — trust score low despite seniority.",
    },
    {
        "id": 4,
        "name": "Priya R.",
        "member_since": "5 years",
        "bookings": 47,
        "past_disputes": 1,
        "refund_requests": 2,
        "trust_score": 94,
        "verified": True,
        "device": "Known device",
        "account_status": "ID Verified ✓✓",
        "pipeline_note": "Power user. Fastest path, maximum benefit of doubt, large refunds auto-approved.",
        "story": "Frequent traveler, near-perfect record, ID verified. Top tier trust.",
    },
    {
        "id": 5,
        "name": "Jamie L.",
        "member_since": "8 months",
        "bookings": 3,
        "past_disputes": 0,
        "refund_requests": 1,
        "trust_score": 51,
        "verified": False,
        "device": "Known device",
        "account_status": "Email only",
        "pipeline_note": "Medium trust. Verification prompt triggered before high-stakes actions.",
        "story": "Real user but never completed ID verification. Limited refund ceiling until verified.",
    },
    {
        "id": 6,
        "name": "User 9823",
        "member_since": "3 days",
        "bookings": 0,
        "past_disputes": 0,
        "refund_requests": 0,
        "trust_score": 12,
        "verified": False,
        "device": "New device — VPN detected",
        "account_status": "Unverified",
        "pipeline_note": "Maximum scrutiny. Human review required. No automated action possible.",
        "story": "Red flags across the board. Could be fraud, could be legitimate. System can't tell.",
    },
    {
        "id": 7,
        "name": "Chen W.",
        "member_since": "4 years",
        "bookings": 22,
        "past_disputes": 3,
        "refund_requests": 3,
        "trust_score": 62,
        "verified": True,
        "device": "Known device",
        "account_status": "Verified ✓",
        "pipeline_note": "Had disputes 2 years ago, clean since. Score recovering. Standard queue but monitored.",
        "story": "Reformed history — past disputes offset by recent clean record.",
    },
    {
        "id": 8,
        "name": "David S. — TechCorp",
        "member_since": "2 years",
        "bookings": 89,
        "past_disputes": 2,
        "refund_requests": 8,
        "trust_score": 78,
        "verified": True,
        "device": "Known device",
        "account_status": "Business Verified ✓",
        "pipeline_note": "Business travel account. Higher refund ceiling, different escalation path.",
        "story": "High volume corporate account. Disputes expected at this booking frequency.",
    },
    {
        "id": 9,
        "name": "Maria G.",
        "member_since": "1 year",
        "bookings": 4,
        "past_disputes": 0,
        "refund_requests": 1,
        "trust_score": 71,
        "verified": True,
        "device": "Known device",
        "account_status": "Verified ✓",
        "pipeline_note": "Clean account but query signals emotional distress. Empathy mode, extenuating circumstances policy retrieved.",
        "story": "Bereavement or family emergency scenario. Good trust score but sensitive situation.",
    },
    {
        "id": 10,
        "name": "Robert F.",
        "member_since": "6 years",
        "bookings": 8,
        "past_disputes": 0,
        "refund_requests": 0,
        "trust_score": 58,
        "verified": True,
        "device": "Unknown — new device",
        "account_status": "Verified ✓",
        "pipeline_note": "Old account, long inactive, unknown device triggers re-scoring. Re-verification prompted.",
        "story": "6-year member but barely used. New device suddenly active — system flags for re-authentication.",
    },
]

def get_random_profile():
    import random
    return random.choice(PROFILES)

def get_profile_by_id(profile_id: int):
    return next((p for p in PROFILES if p["id"] == profile_id), PROFILES[0])
